name: "Create collection"

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'OpenAPI filepath'     
        required: true
        default: 'adyen-openapi/yaml/CheckoutService-v70.yaml'
      workspaceId:
        description: 'Postman workspace ID'     
        required: true
jobs:
  generate:
    name: "Generate Postman Collection"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/checkout@v3
        with:
          repository: 'adyen/adyen-openapi'
          fetch-depth: 0
          path: 'adyen-openapi'
      - uses: addnab/docker-run-action@v3
        with:
          image: gcatanese/openapi-generator-postman-v2
          options: -v ${{ github.workspace }}:/usr/src/app
          run: |
            /usr/src/app/createCollection.sh ${{ github.event.inputs.file }} ${{ secrets.POSTMAN_API_KEY }} ${{ github.event.inputs.workspaceId }} 
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Manual generation"