# Update the IPP collection

name: "In-person payments"

on:
  push:
    branches: [ main ]
    paths:
      - 'in-person-payments/ipp.json'

permissions:
  contents: read  
  
jobs:
  push:
    name: "Update Postman Collection"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - name: push-to-postman-action
        id: push-to-postman
        uses: gcatanese/push-to-postman-action@main
        with:
          goal: update
          postman-key: ${{ secrets.POSTMAN_API_KEY }}
          postman-file: 'in-person-payments/ipp.json'
          collection-id: ${{ secrets.POSTMAN_IPP_COLLECTION_ID }}
