name: "Generate latest definitions files"

env:
  VS_WORKFLOW_TYPE: "trigger-postman"

on:
  workflow_dispatch:

jobs:
  issue:
    name: "Creating GitHub update issue"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          repository: 'Adyen/adyen-openapi'
          path: 'adyen-openapi'
          fetch-depth: 0
      - run: ls
      - run: echo "$$$$$$$$$$"
      - run: ls adyen-openapi
      - name: Get changed files in the yaml folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: adyen-openapi/yaml/*.yaml
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILENAMES: ${{ steps.changed-files-specific.outputs.all_changed_files }}
        with:
          filename: .github/ISSUE_TEMPLATE/openapi-changes.yml
  generate:
    name: "Generate latest definitions files"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/checkout@v3
        with:
          repository: 'Adyen/adyen-openapi'
          fetch-depth: 0
          path: 'adyen-openapi'
      - uses: addnab/docker-run-action@v3
        with:
          image: gcatanese/openapi-generator-postman-v2
          options: -v ${{ github.workspace }}:/usr/src/app
          run: |
            /usr/src/app/generateAll.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update latest definitions files"