name: "Generate latest definitions files"

env:
  VS_WORKFLOW_TYPE: "trigger-postman"

on:
  workflow_dispatch:

jobs:
  generate:
    name: "Generate latest definitions files"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/checkout@v4
        with:
          repository: 'Adyen/adyen-openapi'
          fetch-depth: 0
          path: 'adyen-openapi'
      - uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/adyen-examples/openapi-generator-postman-v2:main
          options: -v ${{ github.workspace }}:/usr/src/app
          run: |
            /usr/src/app/generateAll.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update latest definitions files"
